// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiftmexmxeynbrtsovsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZnRtZXhteGV5bmJydHNvdnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTI5MzQsImV4cCI6MjA3NDUyODkzNH0.iYNbXQnbrmrcYMfIEHJwbmnW859XKdH6Llzx3EsjSS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});